version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./build/docker/app/Dockerfile
    tty: true
    ports:
      - "8080:8080"
    environment:
      APP_PORT: 8080
      APP_DBHOST: db
      APP_DBPORT: 3306
      APP_DBUSERNAME: root
      APP_DBPASSWORD: password
      APP_DBNAME: todo_api_dev
      APP_SECRETKEY: JDJhJDEwJDE5clFvMFJJdkI1T0xBSlF6ci50Ny42am84Vjd4YXYwYVN0UHFuZTF4N1ZlbzFHdjBzd0dh
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - mysql-datavolume:/var/lib/mysql
      - ./build/docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - ./build/docker/db/docker.mysql.env
    ports:
      - 3306:3306
    platform: linux/x86_64

volumes:
  mysql-datavolume:
    driver: local

